# docker-compose.yml
version: '3.9'

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: users-db
      POSTGRES_USER: user_postgres_username
      POSTGRES_PASSWORD: user_postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: user_postgres_username
      KC_DB_PASSWORD: user_postgres_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: