rootProject.name = 'Strawberries'

include ':api:user-api'
include ':api:product-api'
include ':api:product-rpc'
include ':api:order-api'
include ':api:cart-api'
include ':api:cart-rpc'
include ':api:product-rpc'

include ':service:user-service'
include ':service:product-service'
include ':service:order-service'
include ':service:cart-service'

include ':event:order-events-contract'
